name = "lastfm-proxy"
compatibility_date = "2022-12-04"
main = "src/index.ts"

[vars]
LASTFM_USERNAME = "BrianMitchL"
# echo <VALUE> | wrangler secret put LASTFM_API_KEY

[env.dev]
name = "lastfm-proxy-dev"

[env.dev.vars]
LASTFM_USERNAME = "BrianMitchL"
# echo <VALUE> | wrangler secret put LASTFM_API_KEY --env=dev
