name = "lastfm-proxy"
compatibility_date = "2022-12-04"
main = "src/index.ts"
route = "lastfm-proxy.brianm.me/*"

[vars]
LASTFM_USERNAME = "BrianMitchL"
# echo <VALUE> | wrangler secret put LASTFM_API_KEY

[env.dev]
name = "lastfm-proxy-dev"
route = "lastfm-proxy-dev.brianm.me/*"

[env.dev.vars]
LASTFM_USERNAME = "BrianMitchL"
# echo <VALUE> | wrangler secret put LASTFM_API_KEY --env=dev
